# Generated by Django 3.0.3 on 2020-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_gameitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='topics',
            field=models.ManyToManyField(to='gamedata.Topic'),
        ),
    ]
