# Generated by Django 3.0.3 on 2020-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_auto_20200226_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
