# Generated by Django 3.0.3 on 2020-02-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0004_topic_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, max_length=255, null=True)),
                ('developer', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('release_date', models.DateField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.CharField(max_length=255)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField(null=True)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='gameitem',
            name='game',
        ),
        migrations.DeleteModel(
            name='gamedata',
        ),
        migrations.DeleteModel(
            name='gameitem',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game_type'),
        ),
    ]
