# Generated by Django 3.0.3 on 2020-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_auto_20200227_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image_url',
            field=models.ImageField(upload_to='static/static_dirs/images/'),
        ),
    ]
