# Generated by Django 3.0.3 on 2020-03-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_auto_20200309_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_games',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game'),
        ),
    ]
