# Generated by Django 3.0.3 on 2020-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0009_auto_20200309_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
